#!/bin/bash

OS=`uname -s`

if [[ $OS == "Linux" ]]; then
    TRYGREP=`man -k . | grep 3erl | awk '{print \$1}'`
    if [[ -z "$TRYGREP" ]]; then
        MANPATHS=("/usr/lib64/erlang/man" "/usr/local/lib/erlang/man")
        for M in "${MANPATHS[@]}"
        do
            if [ -d $M ]; then
                find $M/man*/ -type f -exec basename {} \; | awk -F'.' '{print $1}' | sort
            fi
        done
    else
        echo "$TRYGREP"
    fi
elif [[ $OS == "Darwin" ]]; then
    OTP=`erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell` | cut -d "\"" -f 2
    MANPATH="/usr/local/Cellar/erlang/$OTP/lib/erlang/man"
    find $MANPATH/man*/ -type f -exec basename {} \; | awk -F'.' '{print $1}' | sort
fi
