#!/bin/bash

OS=`uname -s`

if [[ $OS == "Linux" ]]; then
    TRYGREP=`man -k . | grep 3erl | awk '{print \$1}'`
    if [[ -z "$TRYGREP" ]]; then
        KERLPATH=`kerl active | sed -e 's/^[^/].*$//' -e '/^$/d'`
        MANPATHS=("/usr/lib64/erlang/man" "/usr/local/lib/erlang/man" "$KERLPATH/man")
        for M in "${MANPATHS[@]}"
        do
            if [ -d $M ]; then
                find $M/man*/ -type f -exec basename {} \; | awk -F'.' '{print $1}' | sort
            fi
        done
    else
        echo "$TRYGREP"
    fi
elif [[ $OS == "Darwin" ]]; then
    MANPATH="/usr/local/lib/erlang/man"
    find $MANPATH/man*/ -type f -exec basename {} \; | awk -F'.' '{print $1}' | sort
fi
